source 'http://rubygems.org'

gem 'rails', '3.2.16'
gem 'rake'
gem 'jquery-rails'
gem 'properties-ruby'
gem 'selenium-webdriver', '~>2.44.0'
gem 'rspec-rails'
gem 'rspec'
gem 'yarjuf'
gem 'rspec_junit_formatter'
gem 'rspec-extra-formatters'
gem 'rest-client'
gem 'certified'
gem 'logging'
gem 'sys-proctable'
gem 'addressable'
gem 'pry'
gem 'parallel_tests'
gem 'rspec-instafail'
gem 'ruby-gmail'
gem 'waitutil'
gem 'gmail'
gem 'rspec-rerun-failed'
gem 'rspec_log_formatter'
gem 'allure-rspec'
gem 'nokogiri'
gem 'uuid'
gem 'rspec-retry'
gem 'rspec-legacy_formatters'
